### ISSUE TITLE
Is it PST or PDT?

### ISSUE THREAD

**Issue by Jennifer88huang-zz** [streamnative/tgip#54]
I notice in the readme, it says "PST". In our promotion assets, it's "PDT". Which one do we use?
![image](https://user-images.githubusercontent.com/47805623/89023479-364ebf00-d356-11ea-9dd8-ba56aa623459.png)

**Comment by tuhaihe** [comment]
PDT is short for Pacific Daylight Time, PST is short for Pacific Standard Time. 

> PDT是Pacific Daylight Time太平洋夏季时间。美国西海岸(旧金山 洛杉矶 西雅图 波特兰)在夏时制时用这一时间。美国夏季始于每年4月的第1个周日，止于每年10月的最后一个周日。夏令时比正常时间早一小时。相对应的是PST , Pacific Standard Time 。 夏时制结束后就是PST。

So we can reuse PST in our future promotion assets.
