### ISSUE TITLE
Episode 019: Understand the flow control mechanism in Pulsar consumers

### ISSUE THREAD

**Issue by SylviaBABY** [streamnative/tgip#59]
- [x] Topic: Understand the flow control mechanism in Pulsar consumers

- [x] Instructor: Sijie Guo

- [x] Date: 2020/09/18

- [x] Time: 1PM PDT

- [x] Duration: 1h

- [x] Registration link: zoom link(no)

- [x] Live streaming link: https://www.youtube.com/channel/UCywxUI5HlIyc0VEKYR4X9Pg/live

**Comment by Jennifer88huang-zz** [comment]
@JipeiWang please take over this task, thank you.

**Comment by JipeiWang** [comment]
I think we can close this issue since @SylviaBABY is back.
